name: "release"

on:
    release:
        types: [published]
jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: node
            uses: actions/setup-node@v2
            with:
                node-version: 14
                registry-url: https://registry.npmjs.org
          - name: add vue-cli-services
            run: npm i @vue/cli-service
          - name: publish
            run: npm publish --access public
            env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
